server {
    server_name coda.irazu.com.ar;

    # Access and error logs
    access_log /var/log/nginx/coda_access.log;
    error_log /var/log/nginx/coda_error.log;

    # Certbot ACME challenge location
    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type "text/plain";
        try_files $uri =404;
    }

    location /icons/ {
        root /www/coda;
        try_files $uri =404;
    }

    location /photos/ {
        root /www/coda;
        try_files $uri =404;
    }

    # Serve static files for SPA
    location / {
        root /www/coda;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Cross-Origin-Opener-Policy "same-origin-allow-popups" always;
    add_header Cross-Origin-Embedder-Policy "credentialless" always;

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/coda.irazu.com.ar/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/coda.irazu.com.ar/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = coda.irazu.com.ar) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    server_name coda.irazu.com.ar;

    listen 80;
    return 404; # managed by Certbot
}
